CREATE TABLE "SECCION" (
	"CODIGO_SEC" serial NOT NULL,
	"NOMBRE_SEC" varchar(200) NOT NULL,
	"ESTADO_SEC" varchar(1) NOT NULL,
	"FECHA_ACT_SEC" DATE NOT NULL,
	CONSTRAINT SECCION_pk PRIMARY KEY ("CODIGO_SEC")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "MATERIA" (
	"CODIGO_MAT" serial NOT NULL,
	"NOMBRE_MAT" varchar(200) NOT NULL,
	"ESTADO_MAT" varchar(1) NOT NULL,
	"FECHA_ACT_MAT" DATE NOT NULL,
	CONSTRAINT MATERIA_pk PRIMARY KEY ("CODIGO_MAT")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "TIPO_NORMA" (
	"CODIGO_TN" serial NOT NULL,
	"NOMBRE_TN" varchar(200) NOT NULL,
	"ESTADO_TN" varchar(1) NOT NULL,
	"FECHA_ACT_TN" DATE NOT NULL,
	CONSTRAINT TIPO_NORMA_pk PRIMARY KEY ("CODIGO_TN")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "TIPO_PUBLICACION" (
	"CODIGO_TP" serial NOT NULL,
	"NOMBRE_TP" varchar(200) NOT NULL,
	"ESTADO_TP" varchar(1) NOT NULL,
	"FECHA_ACT_TP" DATE NOT NULL,
	CONSTRAINT TIPO_PUBLICACION_pk PRIMARY KEY ("CODIGO_TP")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "DOCUMENTO" (
	"CODIGO_DOC" serial NOT NULL,
	"TITULO_DOC" varchar(500) NOT NULL,
	"NUMERO_DOC" integer NOT NULL,
	"FECHA_FIRMA_DOC" DATE NOT NULL,
	"FECHA_PUBLICACION_DOC" DATE NOT NULL,
	"ESTADO_DOC" varchar NOT NULL,
	"FECHA_ACT_DOC" DATE NOT NULL,
	"CODIGO_MAT" integer NOT NULL,
	"CODIGO_TN" integer NOT NULL,
	"CODIGO_TP" integer NOT NULL,
	"RUTA_DOC" varchar(1000) NOT NULL,
	"CODIGO_SEC" integer NOT NULL,
	CONSTRAINT DOCUMENTO_pk PRIMARY KEY ("CODIGO_DOC")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "RESULTADO_BUSQUEDA" (
	"CODIGO_RB" serial NOT NULL,
	"TEXTO_RB" varchar(1000) NOT NULL,
	"FECHA_RB" DATE NOT NULL,
	"USUARIO_RB" integer NOT NULL,
	"CODIGO_DOC" integer NOT NULL,
	CONSTRAINT RESULTADO_BUSQUEDA_pk PRIMARY KEY ("CODIGO_RB")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "ROL" (
	"CODIGO_ROL" serial NOT NULL,
	"NOMBRE_ROL" varchar(500) NOT NULL,
	"ESTADO_ROL" varchar(1) NOT NULL,
	"FECHA_ACT_ROL" DATE NOT NULL,
	"CODIGO_TR" integer NOT NULL,
	CONSTRAINT ROL_pk PRIMARY KEY ("CODIGO_ROL")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "TIPO_ROL" (
	"CODIGO_TR" serial NOT NULL,
	"NOMBRE_TR" varchar(500) NOT NULL,
	"ESTADO_TR" varchar(1) NOT NULL,
	"FECHA_ACT_TR" DATE NOT NULL,
	CONSTRAINT TIPO_ROL_pk PRIMARY KEY ("CODIGO_TR")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "USUARIO" (
	"CODIGO_US" serial NOT NULL,
	"NOMBRE_US" varchar(500) NOT NULL,
	"ESTADO_US" varchar(1) NOT NULL,
	"FECHA_ACT_US" DATE NOT NULL,
	CONSTRAINT USUARIO_pk PRIMARY KEY ("CODIGO_US")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "USUARIO_CLAVE" (
	"CODIGO_USC" serial NOT NULL,
	"CLAVE_USC" varchar(500) NOT NULL,
	"ESTADO_USC" varchar(1) NOT NULL,
	"FECHA_ACT_USC" DATE NOT NULL,
	"CODIGO_US" integer NOT NULL,
	CONSTRAINT USUARIO_CLAVE_pk PRIMARY KEY ("CODIGO_USC")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "USUARIO_ROL" (
	"CODIGO_USR" serial NOT NULL,
	"ESTADO_USR" varchar(1) NOT NULL,
	"FECHA_ACT_USR" DATE NOT NULL,
	"CODIGO_ROL" integer NOT NULL,
	"CODIGO_US" integer NOT NULL,
	CONSTRAINT USUARIO_ROL_pk PRIMARY KEY ("CODIGO_USR")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "PAIS" (
	"CODIGO_PAIS" serial NOT NULL,
	"NOMBRE_PAIS" varchar(200) NOT NULL,
	CONSTRAINT PAIS_pk PRIMARY KEY ("CODIGO_PAIS")
) WITH (
  OIDS=FALSE
);







ALTER TABLE "DOCUMENTO" ADD CONSTRAINT "DOCUMENTO_fk0" FOREIGN KEY ("CODIGO_MAT") REFERENCES "MATERIA"("CODIGO_MAT");
ALTER TABLE "DOCUMENTO" ADD CONSTRAINT "DOCUMENTO_fk1" FOREIGN KEY ("CODIGO_TN") REFERENCES "TIPO_NORMA"("CODIGO_TN");
ALTER TABLE "DOCUMENTO" ADD CONSTRAINT "DOCUMENTO_fk2" FOREIGN KEY ("CODIGO_TP") REFERENCES "TIPO_PUBLICACION"("CODIGO_TP");
ALTER TABLE "DOCUMENTO" ADD CONSTRAINT "DOCUMENTO_fk3" FOREIGN KEY ("CODIGO_SEC") REFERENCES "SECCION"("CODIGO_SEC");

ALTER TABLE "RESULTADO_BUSQUEDA" ADD CONSTRAINT "RESULTADO_BUSQUEDA_fk0" FOREIGN KEY ("USUARIO_RB") REFERENCES "USUARIO"("CODIGO_US");
ALTER TABLE "RESULTADO_BUSQUEDA" ADD CONSTRAINT "RESULTADO_BUSQUEDA_fk1" FOREIGN KEY ("CODIGO_DOC") REFERENCES "DOCUMENTO"("CODIGO_DOC");

ALTER TABLE "ROL" ADD CONSTRAINT "ROL_fk0" FOREIGN KEY ("CODIGO_TR") REFERENCES "TIPO_ROL"("CODIGO_TR");



ALTER TABLE "USUARIO_CLAVE" ADD CONSTRAINT "USUARIO_CLAVE_fk0" FOREIGN KEY ("CODIGO_US") REFERENCES "USUARIO"("CODIGO_US");

ALTER TABLE "USUARIO_ROL" ADD CONSTRAINT "USUARIO_ROL_fk0" FOREIGN KEY ("CODIGO_ROL") REFERENCES "ROL"("CODIGO_ROL");
ALTER TABLE "USUARIO_ROL" ADD CONSTRAINT "USUARIO_ROL_fk1" FOREIGN KEY ("CODIGO_US") REFERENCES "USUARIO"("CODIGO_US");


